### PR TITLE
Add button for resume/cv

### LINKED ISSUE #16: Add Resume/CV
From MLH-Fellowship/pod-3.1.2-portfolio [Issue 1](https://github.com/MLH-Fellowship/pod-3.1.2-portfolio/issues/1#issue-944643770)

This portfolio acts very like your resume or CV but doesn't contain it. So maybe we can add a button for people to view/download your resume.

### PR DESCRIPTION
**Pull request by sonalsk**
Added button for people to view/download an external resume. 
Fixes #16
## Please, go through these steps before you submit a PR.

- [x] You've explained what the Pull Request is adding.
- [x] You've explained why this is important.

### CODE REVIEW

**Comment by ayushmaang** [comment]
This button is a great start but you should make it actually download your resume. Right now it'll just take you to google drive.

**Comment by sonalsk** [comment]
> This button is a great start but you should make it actually download your resume. Right now it'll just take you to google drive.

That is a good idea. I will fix the issue. Thank you.

**Comment by ayushmaang** [comment]
Looks solid now.

**Comment by ayushmaang** [comment]
Just fix the merge conflict.

**Comment by sonalsk** [comment]
> Just fix the merge conflict.

Resolved

**Pull request merged**
